export const BACKGROUND_THEME_PROFILES = {
  quake: {
    category: 'aggressive',
    cssClass: 'bg-theme-quake bg-cat-aggressive bg-heat-haze',
    parallax: 11,
  },
  lava: {
    category: 'aggressive',
    cssClass: 'bg-theme-lava bg-cat-aggressive bg-heat-haze',
    parallax: 12,
  },
  inferno: {
    category: 'aggressive',
    cssClass: 'bg-theme-inferno bg-cat-aggressive bg-heat-haze',
    parallax: 13,
  },
  storm: {
    category: 'aggressive',
    cssClass: 'bg-theme-storm bg-cat-aggressive',
    parallax: 10,
    preferCanvas: true,
    vanta: {
      type: 'waves',
      color: 0x3f246a,
      backgroundColor: 0x020205,
      shininess: 62,
      waveHeight: 42,
      waveSpeed: 3.4,
      zoom: 0.52,
    },
  },
  ember: {
    category: 'aggressive',
    cssClass: 'bg-theme-ember bg-cat-aggressive bg-heat-haze',
    parallax: 10,
  },
  volcano: {
    category: 'aggressive',
    cssClass: 'bg-theme-volcano bg-cat-aggressive bg-heat-haze',
    parallax: 11,
  },

  ocean: {
    category: 'fluid',
    cssClass: 'bg-theme-ocean bg-cat-fluid bg-depth-soft',
    parallax: 8,
    preferCanvas: true,
    vanta: {
      type: 'waves',
      color: 0x0d5e89,
      backgroundColor: 0x01070f,
      shininess: 48,
      waveHeight: 15,
      waveSpeed: 0.42,
      zoom: 0.83,
    },
  },
  bubbles: {
    category: 'fluid',
    cssClass: 'bg-theme-bubbles bg-cat-fluid bg-depth-soft',
    parallax: 8,
    preferCanvas: true,
    vanta: {
      type: 'waves',
      color: 0x0d95a7,
      backgroundColor: 0x021018,
      shininess: 66,
      waveHeight: 12,
      waveSpeed: 0.5,
      zoom: 0.9,
    },
  },
  glacier: {
    category: 'fluid',
    cssClass: 'bg-theme-glacier bg-cat-fluid bg-depth-soft',
    parallax: 7,
    preferCanvas: true,
    vanta: {
      type: 'cells',
      color1: 0x7ea4c7,
      color2: 0xc5eeff,
      size: 2.7,
      speed: 0.18,
    },
  },
  clouds: {
    category: 'fluid',
    cssClass: 'bg-theme-clouds bg-cat-fluid bg-depth-soft',
    parallax: 7,
    preferCanvas: true,
    vanta: {
      type: 'clouds',
      backgroundColor: 0x050d17,
      skyColor: 0x071321,
      cloudColor: 0x2f6d86,
      speed: 0.26,
      zoom: 1.14,
    },
  },
  deepsea: {
    category: 'fluid',
    cssClass: 'bg-theme-deepsea bg-cat-fluid bg-depth-soft',
    parallax: 8,
    vanta: {
      type: 'clouds',
      backgroundColor: 0x020b10,
      skyColor: 0x05141d,
      cloudColor: 0x00d9e6,
      speed: 0.32,
      zoom: 1.08,
    },
  },

  stars: {
    category: 'cosmic',
    cssClass: 'bg-theme-stars bg-cat-cosmic',
    parallax: 6,
    preferCanvas: true,
    vanta: {
      type: 'dots',
      backgroundColor: 0x000000,
      color: 0xe8f3ff,
      color2: 0x99f7ff,
      size: 2.1,
      spacing: 15,
      showLines: false,
    },
  },
  nebula: {
    category: 'cosmic',
    cssClass: 'bg-theme-nebula bg-cat-cosmic',
    parallax: 7,
    preferCanvas: true,
    vanta: {
      type: 'fog',
      highlightColor: 0x8ad4ff,
      midtoneColor: 0x2e1762,
      lowlightColor: 0x060211,
      baseColor: 0x000000,
      blurFactor: 0.62,
      speed: 0.6,
      zoom: 1.18,
    },
  },
  warp: {
    category: 'cosmic',
    cssClass: 'bg-theme-warp bg-cat-cosmic bg-center-pull',
    parallax: 9,
    preferCanvas: true,
    vanta: {
      type: 'halo',
      backgroundColor: 0x000003,
      amplitude: 3.0,
      size: 0.95,
      xOffset: 0,
      yOffset: 0,
      color: 0x9ad5ff,
    },
  },
  blackhole: {
    category: 'cosmic',
    cssClass: 'bg-theme-blackhole bg-cat-cosmic bg-center-pull',
    parallax: 9,
    preferCanvas: true,
    vanta: {
      type: 'halo',
      backgroundColor: 0x000000,
      amplitude: 3.45,
      size: 0.78,
      xOffset: 0,
      yOffset: 0,
      color: 0xcf89ff,
    },
  },
  abyss: {
    category: 'cosmic',
    cssClass: 'bg-theme-abyss bg-cat-cosmic',
    parallax: 6,
    preferCanvas: true,
    vanta: {
      type: 'fog',
      highlightColor: 0x7d5ad1,
      midtoneColor: 0x14061f,
      lowlightColor: 0x020103,
      baseColor: 0x000000,
      blurFactor: 0.8,
      speed: 0.25,
      zoom: 1.45,
    },
  },
  stellar: {
    category: 'cosmic',
    cssClass: 'bg-theme-stellar bg-cat-cosmic',
    parallax: 8,
    vanta: {
      type: 'halo',
      backgroundColor: 0x000000,
      amplitude: 2.9,
      size: 1.25,
      xOffset: 0.05,
      yOffset: -0.02,
      color: 0xffe4ba,
    },
  },

  matrix: {
    category: 'digital',
    cssClass: 'bg-theme-matrix bg-cat-digital',
    parallax: 6,
    preferCanvas: true,
    vanta: {
      type: 'net',
      color: 0x39ff72,
      backgroundColor: 0x000500,
      points: 24,
      maxDistance: 26,
      spacing: 11,
      showDots: true,
    },
  },
  grid: {
    category: 'digital',
    cssClass: 'bg-theme-grid bg-cat-digital',
    parallax: 7,
    preferCanvas: true,
    vanta: {
      type: 'net',
      color: 0x66d9ff,
      backgroundColor: 0x020912,
      points: 18,
      maxDistance: 22,
      spacing: 18,
      showDots: true,
    },
  },
  geometry: {
    category: 'digital',
    cssClass: 'bg-theme-geometry bg-cat-digital',
    parallax: 9,
    vanta: {
      type: 'net',
      color: 0xff2fb4,
      backgroundColor: 0x030007,
      points: 15,
      maxDistance: 26,
      spacing: 20,
      showDots: true,
    },
  },
  ritual: {
    category: 'digital',
    cssClass: 'bg-theme-ritual bg-cat-digital',
    parallax: 8,
    vanta: {
      type: 'fog',
      highlightColor: 0xffd75b,
      midtoneColor: 0x4a125d,
      lowlightColor: 0x170426,
      baseColor: 0x010001,
      speed: 0.58,
      zoom: 1.52,
    },
  },
  oiia: {
    category: 'digital',
    cssClass: 'bg-theme-oiia bg-cat-digital bg-meme-kaleido',
    parallax: 10,
  },
  nyancat: {
    category: 'digital',
    cssClass: 'bg-theme-nyancat bg-cat-digital bg-meme-stripes',
    parallax: 10,
  },

  crystal: {
    category: 'other',
    cssClass: 'bg-theme-crystal bg-cat-fluid bg-depth-soft',
    parallax: 8,
    preferCanvas: true,
    vanta: {
      type: 'cells',
      color1: 0x2f57b8,
      color2: 0x65edff,
      size: 1.8,
      speed: 0.44,
    },
  },
  forest: {
    category: 'other',
    cssClass: 'bg-theme-forest bg-cat-fluid',
    parallax: 8,
  },
  aurora: {
    category: 'other',
    cssClass: 'bg-theme-aurora bg-cat-fluid bg-depth-soft',
    parallax: 8,
    preferCanvas: true,
    vanta: {
      type: 'cells',
      color1: 0x0b3b4c,
      color2: 0x3affbe,
      size: 1.38,
      speed: 0.36,
    },
  },
  custom: {
    category: 'other',
    cssClass: 'bg-theme-custom',
    parallax: 6,
  },
}

export const BACKGROUND_DEFAULT_PROFILE = {
  category: 'other',
  cssClass: 'bg-theme-default',
  parallax: 7,
}

export const BGTYPE_VANTA_CONFIG = Object.fromEntries(
  Object.entries(BACKGROUND_THEME_PROFILES)
    .filter(([, profile]) => profile?.vanta?.type)
    .map(([bgType, profile]) => [bgType, profile.vanta]),
)

export function getBackgroundProfile(bgType) {
  return BACKGROUND_THEME_PROFILES[bgType] || BACKGROUND_DEFAULT_PROFILE
}
