// Season 5 - The Pantheon Arc
// Eleven sequential boss encounters culminating in Aetherion.

import { isDevMode } from './devMode'
import { isS4Complete } from './storyData_s4'

export const PANTHEON_BOSSES = [
  {
    id: 'atlas',
    name: 'Atlas',
    subtitle: 'The Weight of Heaven',
    glyph: 'Ω',
    color: '#d7a84b',
    glowColor: '#ffe09a',
    bgType: 'gold_wireframe',
    bpm: 92,
    gravityMult: 2.15,
    targetLines: 45,
    easyTargetLines: 36,
    ability: 'sticky_inputs',
    abilityLabel: 'WORLDWEIGHT',
    abilityDesc: 'Gravity crushes every piece downward while divine pressure delays movement and rotation inputs.',
    storyBefore: 'I have carried the sky since before mortals learned to name it. Take one step beneath my burden, Weaver, and learn how heavy eternity truly is.',
    storyAfter: 'For one impossible breath, the heavens rest upon your shoulders. You do not kneel. Pass onward, burden-bearer.',
  },
  {
    id: 'tyche',
    name: 'Tyche',
    subtitle: 'Lady of the Crooked Lot',
    glyph: 'ϟ',
    color: '#ff4fa3',
    glowColor: '#ff9dca',
    bgType: 'fractal_madness',
    bpm: 148,
    gravityMult: 1.18,
    targetLines: 45,
    easyTargetLines: 36,
    mechanic: 'mirage_blocks',
    ability: 'worst_piece',
    abilityLabel: 'LOADED FATE',
    abilityDesc: 'Mirage Blocks conceal their true shape, and Fate selects the most damaging piece whenever your board is vulnerable.',
    storyBefore: 'Skill is the bedtime story mortals tell themselves when fortune smiles. I have weighted every coin, marked every die, and poisoned every bag.',
    storyAfter: 'The impossible draw arrived, and still you found a place for it. Perhaps fortune is not sovereign after all.',
  },
  {
    id: 'erebus',
    name: 'Erebus',
    subtitle: 'The Hunger Between Stars',
    glyph: '◉',
    color: '#7857ff',
    glowColor: '#b7a8ff',
    bgType: 'void_purple',
    bpm: 76,
    gravityMult: 1.05,
    targetLines: 46,
    easyTargetLines: 37,
    mechanic: 'void_zones_heavy',
    ability: 'void_zones_heavy',
    abilityLabel: 'NULL THRONE',
    abilityDesc: 'Your Hold chamber is erased and moving Void Zones consume blocks placed inside them.',
    storyBefore: 'Before the first light, there was only me. Give me your reserve, your certainty, your carefully prepared escape. The void keeps all gifts.',
    storyAfter: 'You filled absence with intention. Even the eldest dark must make room for what you have built.',
  },
  {
    id: 'chronos',
    name: 'Chronos',
    subtitle: 'Keeper of the Last Second',
    glyph: '⌛',
    color: '#55d6ff',
    glowColor: '#b6efff',
    bgType: 'upside_down_matrix',
    bpm: 120,
    gravityMult: 1.22,
    targetLines: 48,
    easyTargetLines: 38,
    ability: 'clear_lag',
    abilityLabel: 'BORROWED SECONDS',
    abilityDesc: 'Cleared lines remain solid for several seconds before time releases them from the board.',
    storyBefore: 'You mistake motion for progress. Every line you clear belongs to me until I decide its moment has passed.',
    storyAfter: 'The clock obeyed. You did not. Go, while there are still moments beyond my reach.',
  },
  {
    id: 'mnemosyne',
    name: 'Mnemosyne',
    subtitle: 'She Who Remembers Every Board',
    glyph: 'Ψ',
    color: '#78e6c1',
    glowColor: '#c4ffec',
    bgType: 'matrix_green_rain',
    bpm: 108,
    gravityMult: 1.12,
    targetLines: 48,
    easyTargetLines: 38,
    mechanic: 'rewind_heavy',
    ability: 'rewind_heavy',
    abilityLabel: 'PERFECT RECALL',
    abilityDesc: 'The board periodically rewinds to an earlier state while the line target remembers your debt.',
    storyBefore: 'I remember every gap you buried, every misdrop you escaped, every future in which this tower failed. Shall we revisit them?',
    storyAfter: 'Memory offered you a prison, yet you made it a map. I will remember this defeat most clearly of all.',
  },
  {
    id: 'janus',
    name: 'Janus',
    subtitle: 'The Two-Faced Gate',
    glyph: 'Ⅱ',
    color: '#ff9361',
    glowColor: '#ffd0b8',
    bgType: 'mirror_dimension',
    bpm: 132,
    gravityMult: 1.28,
    targetLines: 50,
    easyTargetLines: 40,
    mechanic: 'echo_drops',
    ability: 'echo_drops',
    abilityLabel: 'TWIN CONSEQUENCE',
    abilityDesc: 'Every locked piece casts an Echo Drop on the opposite side of the board.',
    storyBefore: 'Every entrance is an exit. Every choice faces backward as well as forward. Build on one side, and answer to the other.',
    storyAfter: 'Both faces speak the same verdict: the gate is open. Enter, Weaver.',
  },
  {
    id: 'hephaestus',
    name: 'Hephaestus',
    subtitle: 'Smith of Unyielding Forms',
    glyph: '⚒',
    color: '#ff6b35',
    glowColor: '#ffc06f',
    bgType: 'obsidian_core',
    bpm: 138,
    gravityMult: 1.35,
    targetLines: 50,
    easyTargetLines: 40,
    ability: 'petrification',
    abilityLabel: 'DIVINE FORGE',
    abilityDesc: 'Heat-forged cells turn to stone and must be struck by repeated line clears before they break.',
    storyBefore: 'Your pieces are toys of soft light. Mine are hammered beneath a mountain until even deletion fears them.',
    storyAfter: 'A worthy structure is not one that never breaks. It is one remade stronger at the fracture.',
  },
  {
    id: 'eris',
    name: 'Eris',
    subtitle: 'The Laughing Discord',
    glyph: '✶',
    color: '#e35dff',
    glowColor: '#f4b3ff',
    bgType: 'glitch_red',
    bpm: 162,
    gravityMult: 1.42,
    targetLines: 52,
    easyTargetLines: 42,
    ability: 'control_discord',
    abilityLabel: 'SCHISM',
    abilityDesc: 'Movement, rotation, and drop controls periodically exchange meanings without warning.',
    storyBefore: 'Order made you predictable. Let us rename left, unmake clockwise, and see whether instinct survives without language.',
    storyAfter: 'You found rhythm inside contradiction. How terribly, beautifully rude.',
  },
  {
    id: 'nemesis',
    name: 'Nemesis',
    subtitle: 'The Measure of Excess',
    glyph: '⚖',
    color: '#ef476f',
    glowColor: '#ff9bb1',
    bgType: 'shattered_mirror',
    bpm: 144,
    gravityMult: 1.5,
    targetLines: 54,
    easyTargetLines: 43,
    ability: 'hover_garbage',
    abilityLabel: 'RETRIBUTION',
    abilityDesc: 'Greedy clears summon suspended garbage that descends when your combo falters.',
    storyBefore: 'Every triumph creates a debt. Every excess demands correction. Show me how much victory your tower can afford.',
    storyAfter: 'You paid consequence with precision. The scales find no remaining debt.',
  },
  {
    id: 'helios',
    name: 'Helios',
    subtitle: 'The Unblinking Crown',
    glyph: '☉',
    color: '#ffd23f',
    glowColor: '#fff0a6',
    bgType: 'pure_white_grid',
    bpm: 156,
    gravityMult: 1.62,
    targetLines: 56,
    easyTargetLines: 45,
    ability: 'blind_queue',
    abilityLabel: 'WHITE SUN',
    abilityDesc: 'Solar judgment burns away the Next queue and periodically washes the upper board in blinding light.',
    storyBefore: 'Nothing hides beneath my noon. Not your queue, not your fear, not the flaw waiting six pieces below the surface.',
    storyAfter: 'You looked into the crown of day and kept your hands steady. The light yields the road above.',
  },
  {
    id: 'aetherion',
    name: 'Aetherion',
    subtitle: 'Supreme Deity of the Ordered Sky',
    glyph: '♛',
    color: '#f7f1ff',
    glowColor: '#d9b8ff',
    bgType: 'prismatic_void',
    bpm: 180,
    gravityMult: 1.85,
    targetLines: 80,
    easyTargetLines: 64,
    mechanic: 'all_mechanics_mixed',
    mechanics: ['sticky_inputs', 'mirage_blocks', 'void_zones_heavy', 'clear_lag', 'echo_drops', 'shrinking_board'],
    ability: 'divine_judgment',
    abilityLabel: 'DIVINE JUDGMENT',
    abilityDesc: 'An endurance trial cycles through the fallen gods\' powers while Divine Judgment dynamically lowers the board ceiling.',
    storyBefore: 'You have mistaken defeated masks for conquered divinity. I am the law that gave those gods their names. Rise through a shrinking heaven and argue your case.',
    storyAfter: 'Judgment is rendered. A mortal pattern has exceeded divine design. Take the empty throne, Weaver; the Pantheon now answers to you.',
  },
]

export function findPantheonBoss(id) {
  return PANTHEON_BOSSES.find(boss => boss.id === id) ?? null
}

export function isPantheonUnlocked(progress = {}) {
  return isDevMode() || isS4Complete(progress)
}

export function isPantheonLevelUnlocked(bossId, progress = {}) {
  if (!isPantheonUnlocked(progress)) return false
  const bossIndex = PANTHEON_BOSSES.findIndex(boss => boss.id === bossId)
  if (bossIndex < 0) return false
  if (bossIndex === 0 || isDevMode()) return true
  return !!progress[`pantheon_${PANTHEON_BOSSES[bossIndex - 1].id}_completed`]
}

export function isS5Complete(progress = {}) {
  return PANTHEON_BOSSES.every(boss => !!progress[`pantheon_${boss.id}_completed`])
}

export function getNextPantheonBoss(bossId) {
  const bossIndex = PANTHEON_BOSSES.findIndex(boss => boss.id === bossId)
  return bossIndex >= 0 ? PANTHEON_BOSSES[bossIndex + 1] ?? null : null
}
