// ─── Season 2 — The Zodiac Arc ────────────────────────────────────────────────
// 12 freely-accessible zodiac bosses + the hidden 13th (Ophiuchus).
// All bosses are single-level fights: 40 lines normal, 32 lines easy.
// Unlocked after completing ch8_l1 (The Matrix).

export const ZODIAC_BOSSES = [
  {
    id: 'aries',
    name: 'Aries',
    subtitle: 'The Ram',
    glyph: '♈',
    color: '#ff4422',
    glowColor: '#ff7744',
    bgType: 'inferno',
    bpm: 158,
    gravityMult: 1.20,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'meteor_strike',
    abilityLabel: 'METEOR STRIKE',
    abilityDesc: 'Every 5 lines cleared, a fiery garbage block crashes down from above.',
    storyBefore: "You charge blindly into my heavens, mortal. Let us see if your little blocks can withstand the inferno of my ambition!",
    storyAfter: "My fire... burns out. Pass, Weaver, before the embers fade.",
  },
  {
    id: 'taurus',
    name: 'Taurus',
    subtitle: 'The Bull',
    glyph: '♉',
    color: '#44aa44',
    glowColor: '#66cc44',
    bgType: 'forest',
    bpm: 95,
    gravityMult: 0.95,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'tremor',
    abilityLabel: 'TREMOR',
    abilityDesc: 'Every 10 seconds, Taurus stomps — your falling piece hard-drops instantly.',
    storyBefore: "The foundation of the universe is unmoving. Your fragile structures will shatter against my absolute resolve.",
    storyAfter: "An immovable object... bested by an unstoppable force.",
  },
  {
    id: 'gemini',
    name: 'Gemini',
    subtitle: 'The Twins',
    glyph: '♊',
    color: '#cc88ff',
    glowColor: '#dd99ff',
    bgType: 'warp',
    bpm: 130,
    gravityMult: 1.10,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'mirror_image',
    abilityLabel: 'MIRROR IMAGE',
    abilityDesc: 'Every 8 lines, your controls flip — left becomes right for 5 seconds.',
    storyBefore: "Two minds, two paths, one inevitable doom for you. Shall we play our little game of reflections?",
    storyAfter: "We are divided... our harmony, shattered into glass.",
  },
  {
    id: 'cancer',
    name: 'Cancer',
    subtitle: 'The Crab',
    glyph: '♋',
    color: '#2299dd',
    glowColor: '#44bbff',
    bgType: 'ocean',
    bpm: 80,
    gravityMult: 0.85,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'high_tide',
    abilityLabel: 'HIGH TIDE',
    abilityDesc: 'Every 15 seconds, dark mist obscures the bottom 3 rows of the board.',
    storyBefore: "The cosmic tides ebb and flow. I will drown your hopes in the deep, silent celestial sea.",
    storyAfter: "Washed away... return my spirit to the tide.",
  },
  {
    id: 'leo',
    name: 'Leo',
    subtitle: 'The Lion',
    glyph: '♌',
    color: '#ffcc00',
    glowColor: '#ffdd44',
    bgType: 'stellar',
    bpm: 145,
    gravityMult: 1.25,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'solar_flare',
    abilityLabel: 'SOLAR FLARE',
    abilityDesc: 'On a Tetris clear, Leo roars — your Next Queue is hidden for 3 pieces.',
    storyBefore: "Bow before the king of the stars! Your petty puzzle is no match for my blinding glory!",
    storyAfter: "The sun sets... even on the grandest empire.",
  },
  {
    id: 'virgo',
    name: 'Virgo',
    subtitle: 'The Maiden',
    glyph: '♍',
    color: '#88dd88',
    glowColor: '#aaeea4',
    bgType: 'geometry',
    bpm: 110,
    gravityMult: 1.05,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'overgrowth',
    abilityLabel: 'OVERGROWTH',
    abilityDesc: 'Celestial vines occasionally entangle your piece — locking its rotation.',
    storyBefore: "Chaos is a disease upon the cosmos. I shall purify this board and leave no room for your imperfections.",
    storyAfter: "Such beautiful... flawless... destruction.",
  },
  {
    id: 'libra',
    name: 'Libra',
    subtitle: 'The Scales',
    glyph: '♎',
    color: '#ffcc88',
    glowColor: '#ffdda8',
    bgType: 'clouds',
    bpm: 115,
    gravityMult: 1.00,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'imbalance',
    abilityLabel: 'IMBALANCE',
    abilityDesc: 'Build your stack unevenly and Libra punishes you with garbage from below.',
    storyBefore: "The universe demands strict equilibrium. Let us weigh your soul against the falling void.",
    storyAfter: "The scales finally tip... in your favor.",
  },
  {
    id: 'scorpio',
    name: 'Scorpio',
    subtitle: 'The Scorpion',
    glyph: '♏',
    color: '#cc2244',
    glowColor: '#ee3355',
    bgType: 'abyss',
    bpm: 140,
    gravityMult: 1.30,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'poison_blocks',
    abilityLabel: 'POISON BLOCKS',
    abilityDesc: 'Some pieces are poisoned. Clearing a line with one sends gravity to max for 5s.',
    storyBefore: "One sting is all it takes to poison your mind. Try not to panic as the venom takes hold.",
    storyAfter: "My own venom... turns against me. Well played.",
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    subtitle: 'The Centaur',
    glyph: '♐',
    color: '#ff8833',
    glowColor: '#ffaa55',
    bgType: 'nebula',
    bpm: 150,
    gravityMult: 1.35,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'volley',
    abilityLabel: 'VOLLEY',
    abilityDesc: 'Cosmic arrows occasionally sabotage your lines — sending garbage after a clear.',
    storyBefore: "My aim is true, and the shooting stars are my arrows. Dodge this, if you can.",
    storyAfter: "My bow snaps. A masterful shot, Weaver.",
  },
  {
    id: 'capricorn',
    name: 'Capricorn',
    subtitle: 'The Sea-Goat',
    glyph: '♑',
    color: '#8899bb',
    glowColor: '#99aacc',
    bgType: 'glacier',
    bpm: 105,
    gravityMult: 1.10,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'avalanche',
    abilityLabel: 'AVALANCHE',
    abilityDesc: 'Every 5 lines cleared, 2 stone garbage rows surge up from the bottom.',
    storyBefore: "The climb is treacherous, and the peak is reserved only for the enduring. You will fall to the abyss.",
    storyAfter: "I have reached... the precipice... and slipped.",
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    subtitle: 'The Water Bearer',
    glyph: '♒',
    color: '#44ccff',
    glowColor: '#66ddff',
    bgType: 'storm',
    bpm: 125,
    gravityMult: 1.15,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'whirlwind',
    abilityLabel: 'WHIRLWIND',
    abilityDesc: 'Astral winds randomly nudge your falling piece left or right.',
    storyBefore: "Drink deep from the well of cosmic knowledge, or be swept away by the winds of radical change.",
    storyAfter: "The vessel shatters... the waters spill into the endless void.",
  },
  {
    id: 'pisces',
    name: 'Pisces',
    subtitle: 'The Fishes',
    glyph: '♓',
    color: '#7766ee',
    glowColor: '#9988ff',
    bgType: 'serpent',
    bpm: 88,
    gravityMult: 0.90,
    targetLines: 40,
    easyTargetLines: 32,
    ability: 'illusion',
    abilityLabel: 'ILLUSION',
    abilityDesc: 'Tetromino colors constantly cycle — rely on shape alone to place them.',
    storyBefore: "Drift with us into the eternal current. Reality is but a fragile illusion of the waking mind.",
    storyAfter: "The dream ends... we wake to the silence.",
  },
]

// The hidden 13th — unlocked only after all 12 zodiac bosses are defeated
export const OPHIUCHUS = {
  id: 'ophiuchus',
  name: 'Ophiuchus',
  subtitle: 'The Serpent Bearer',
  glyph: '⛎',
  color: '#00ff99',
  glowColor: '#44ffaa',
  bgType: 'serpent',
  bpm: 175,
  gravityMult: 1.80,
  targetLines: 40,
  easyTargetLines: 32,
  ability: 'constriction',
  abilityLabel: 'CONSTRICTION',
  abilityDesc: 'Every 10 lines, the outer columns lock off — the board narrows around you.',
  storyBefore: "They banished me to the dark between the stars. I am the forgotten constellation, the 13th master of this sky. Your little game ends in my coils.",
  storyAfter: "No! The cycle is broken... The stars are yours to command. I fade... into the myth...",
}

/** Return a boss by id (checks 12 + Ophiuchus) */
export function findZodiacBoss(id) {
  if (id === 'ophiuchus') return OPHIUCHUS
  return ZODIAC_BOSSES.find(b => b.id === id) ?? null
}

/** True once all 12 regular zodiac bosses are beaten */
export function allZodiacBeaten(progress) {
  return ZODIAC_BOSSES.every(b => !!progress[`zodiac_${b.id}_completed`])
}

/** True once Ophiuchus is beaten */
export function ophiuchusBeaten(progress) {
  return !!progress['zodiac_ophiuchus_completed']
}

/**
 * Circular positions for the 12 zodiac signs on the map.
 * Returns [{x, y}] in SVG-viewBox 0–100 coordinates, starting from the top (Aries)
 * and going clockwise.
 */
export function getZodiacPositions(cx = 50, cy = 50, r = 35) {
  return ZODIAC_BOSSES.map((_, i) => {
    const angle = (i / 12) * 2 * Math.PI - Math.PI / 2  // start at top
    return {
      x: cx + r * Math.cos(angle),
      y: cy + r * Math.sin(angle),
    }
  })
}
